// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/fanart": {
            "get": {
                "description": "获取 Fanart 配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置",
                    "Fanart"
                ],
                "summary": "获取 Fanart 配置",
                "responses": {}
            },
            "post": {
                "description": "更新 Fanart 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置",
                    "Fanart"
                ],
                "summary": "更新 Fanart 配置",
                "parameters": [
                    {
                        "description": "Fanart 配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.FanartConfig"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/config/libraries": {
            "get": {
                "description": "获取媒体库配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置"
                ],
                "summary": "获取媒体库配置",
                "responses": {}
            },
            "post": {
                "description": "更新媒体库配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置"
                ],
                "summary": "更新媒体库配置",
                "parameters": [
                    {
                        "description": "媒体库配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/config.LibraryConfig"
                            }
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/config/log": {
            "get": {
                "description": "获取日志配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置",
                    "日志"
                ],
                "summary": "获取日志配置",
                "responses": {}
            },
            "post": {
                "description": "更新日志配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置",
                    "日志"
                ],
                "summary": "更新日志配置",
                "parameters": [
                    {
                        "description": "日志配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.LogConfig"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/config/media/custom_word": {
            "get": {
                "description": "获取自定义词配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置"
                ],
                "summary": "获取自定义词配置",
                "responses": {}
            },
            "post": {
                "description": "更新自定义词配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置"
                ],
                "summary": "更新自定义词配置",
                "parameters": [
                    {
                        "description": "自定义词配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.CustomWordConfig"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/config/media/format": {
            "get": {
                "description": "获取媒体格式配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置"
                ],
                "summary": "获取媒体格式配置",
                "responses": {}
            },
            "post": {
                "description": "更新媒体格式配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置"
                ],
                "summary": "更新媒体格式配置",
                "parameters": [
                    {
                        "description": "媒体格式配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.FormatConfig"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/config/tmdb": {
            "get": {
                "description": "获取 TMDB 配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "应用配置",
                    "TMDB"
                ],
                "summary": "获取 TMDB 配置",
                "responses": {}
            },
            "post": {
                "description": "更新 TMDB 配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "应用配置",
                    "TMDB"
                ],
                "summary": "更新 TMDB 配置",
                "parameters": [
                    {
                        "description": "TMDB 配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.TMDBConfig"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/library/archive": {
            "post": {
                "description": "整理一个视频文件及其相关的字幕和音轨文件到指定目录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "媒体库"
                ],
                "summary": "归档媒体文件",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.LibraryArchiveMediaRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/log/recent": {
            "get": {
                "description": "获取最近日志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志"
                ],
                "summary": "获取最近日志",
                "responses": {}
            }
        },
        "/overview/{media_type}/{tmdb_id}": {
            "get": {
                "description": "根据媒体类型和 TMDB ID 获取对应的概述信息",
                "tags": [
                    "TMDB"
                ],
                "summary": "获取媒体概述信息",
                "parameters": [
                    {
                        "enum": [
                            "Movie",
                            "TV"
                        ],
                        "type": "string",
                        "description": "媒体类型",
                        "name": "media_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "tmdb_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "季数",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "集数",
                        "name": "episode",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/poster/{media_type}/{tmdb_id}": {
            "get": {
                "description": "根据媒体类型和 TMDB ID 获取对应的海报图片 URL",
                "tags": [
                    "TMDB"
                ],
                "summary": "获取媒体海报图片",
                "parameters": [
                    {
                        "enum": [
                            "Movie",
                            "TV"
                        ],
                        "type": "string",
                        "description": "媒体类型",
                        "name": "media_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "TMDB ID",
                        "name": "tmdb_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/scrape/video": {
            "post": {
                "description": "刮削视频文件的元数据和相关信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "刮削"
                ],
                "summary": "刮削视频",
                "parameters": [
                    {
                        "description": "刮削请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.ScrapeRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "config.CustomWordConfig": {
            "type": "object",
            "properties": {
                "customization": {
                    "description": "自定义占位置词",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exclude_words": {
                    "description": "自定义排除词",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "identify_word": {
                    "description": "自定义识别词",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "config.FanartConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "api_url": {
                    "type": "string"
                },
                "languages": {
                    "description": "语言顺序",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "config.FormatConfig": {
            "type": "object",
            "properties": {
                "movie": {
                    "description": "电影格式",
                    "type": "string"
                },
                "tv": {
                    "description": "电视剧格式",
                    "type": "string"
                }
            }
        },
        "config.LibraryConfig": {
            "type": "object",
            "properties": {
                "dst_path": {
                    "description": "目标路径",
                    "type": "string"
                },
                "dst_type": {
                    "description": "目标类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.StorageType"
                        }
                    ]
                },
                "name": {
                    "description": "媒体库名称",
                    "type": "string"
                },
                "organize_by_category": {
                    "description": "是否按分类分文件夹",
                    "type": "boolean"
                },
                "organize_by_type": {
                    "description": "是否按类型分文件夹",
                    "type": "boolean"
                },
                "src_path": {
                    "description": "源路径",
                    "type": "string"
                },
                "src_type": {
                    "description": "源类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.StorageType"
                        }
                    ]
                },
                "transfer_type": {
                    "description": "传输类型",
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.TransferType"
                        }
                    ]
                }
            }
        },
        "config.LogConfig": {
            "type": "object",
            "properties": {
                "console_level": {
                    "description": "终端输出日志级别",
                    "type": "string"
                },
                "file_dir": {
                    "description": "日志文件目录",
                    "type": "string"
                },
                "file_level": {
                    "description": "文件日志级别",
                    "type": "string"
                }
            }
        },
        "config.TMDBConfig": {
            "type": "object",
            "properties": {
                "api_key": {
                    "description": "API Key",
                    "type": "string"
                },
                "api_url": {
                    "description": "TMDB API URL",
                    "type": "string"
                },
                "image_url": {
                    "description": "图片 API URL",
                    "type": "string"
                },
                "include_image_language": {
                    "description": "包含的图片语言",
                    "type": "string"
                },
                "language": {
                    "description": "语言",
                    "type": "string"
                }
            }
        },
        "meta.MediaType": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "MediaTypeMovie": "电影",
                "MediaTypeTV": "电视剧",
                "MediaTypeUnknown": "未知"
            },
            "x-enum-descriptions": [
                "未知",
                "电影",
                "电视剧"
            ],
            "x-enum-varnames": [
                "MediaTypeUnknown",
                "MediaTypeMovie",
                "MediaTypeTV"
            ]
        },
        "schemas.FileInfoRequest": {
            "type": "object",
            "required": [
                "path",
                "storage_type"
            ],
            "properties": {
                "path": {
                    "type": "string"
                },
                "storage_type": {
                    "$ref": "#/definitions/storage.StorageType"
                }
            }
        },
        "schemas.LibraryArchiveMediaRequest": {
            "type": "object",
            "required": [
                "dst_dir",
                "src_file"
            ],
            "properties": {
                "dst_dir": {
                    "$ref": "#/definitions/schemas.FileInfoRequest"
                },
                "scrape": {
                    "type": "boolean"
                },
                "src_file": {
                    "$ref": "#/definitions/schemas.FileInfoRequest"
                },
                "transfer_type": {
                    "$ref": "#/definitions/storage.TransferType"
                }
            }
        },
        "schemas.ScrapeRequest": {
            "type": "object",
            "required": [
                "dst_file"
            ],
            "properties": {
                "dst_file": {
                    "$ref": "#/definitions/schemas.FileInfoRequest"
                },
                "media_type": {
                    "$ref": "#/definitions/meta.MediaType"
                },
                "tmdb_id": {
                    "type": "integer"
                }
            }
        },
        "storage.StorageType": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1
            ],
            "x-enum-comments": {
                "StorageLocal": "本地文件系统",
                "StorageUnknown": "未知文件系统"
            },
            "x-enum-descriptions": [
                "未知文件系统",
                "本地文件系统"
            ],
            "x-enum-varnames": [
                "StorageUnknown",
                "StorageLocal"
            ]
        },
        "storage.TransferType": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-comments": {
                "TransferCopy": "复制",
                "TransferLink": "硬链接",
                "TransferMove": "移动",
                "TransferSoftLink": "软链接",
                "TransferUnknown": "未知转移类型"
            },
            "x-enum-descriptions": [
                "未知转移类型",
                "复制",
                "移动",
                "硬链接",
                "软链接"
            ],
            "x-enum-varnames": [
                "TransferUnknown",
                "TransferCopy",
                "TransferMove",
                "TransferLink",
                "TransferSoftLink"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"HTTP"},
	Title:            "MediaTools API 文档",
	Description:      "下一代媒体刮削&整理工具",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
