name: Core Builder for Binary

on:
  workflow_call:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  build-binary-core:
    strategy:
      matrix:
        include:
          - platform: ubuntu-24.04
            goos: linux
            goarch: amd64
          - platform: ubuntu-24.04-arm
            goos: linux
            goarch: arm64

          - platform: macos-latest
            goos: darwin
            goarch: amd64
          - platform: macos-latest
            goos: darwin
            goarch: arm64
          - platform: macos-latest
            goos: darwin
            goarch: universal

          - platform: windows-latest
            goos: windows
            goarch: amd64
          - platform: windows-11-arm
            goos: windows
            goarch: arm64

    name: Build ${{ matrix.goos }}(${{ matrix.goarch }}) Binary Core
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Dependency for Linux
        if: matrix.goos == 'linux'
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-4-dev \
            libwebkit2gtk-4.1-dev

      - name: Setup Dependency for Windows ARM64
        if: matrix.goos == 'windows' && matrix.goarch == 'arm64'
        uses: mlugg/setup-zig@v2

      - name: Download web build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: web/dist/

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0 # 使用低版本通过 GOTOOLCHAIN 自动下载更高版本

      - name: Install CLI Tools
        shell: bash
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Build
        shell: bash
        env:
          GOTOOLCHAIN: auto
          CGO_ENABLED: 1
          GO111MODULE: on
        run: |
          go run scripts/build.go -desktop -os ${{ matrix.goos }} -arch ${{ matrix.goarch }}

      - name: Get Version
        id: get-version
        shell: bash
        run: |
          VERSION=$(go run scripts/build.go -version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MediaTools-${{ matrix.goos }}-${{ matrix.goarch }}-${{ steps.get-version.outputs.version }}
          path: build/bin/*
