name: Core Builder for Docker

on:
  workflow_call:
    inputs:
      IS_LATEST:
        description: "是否发布为 Docker 镜像最新版本"
        required: true
        type: boolean
      VERSION:
        description: "版本号"
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
env:
  IS_LATEST: ${{ inputs.IS_LATEST }}
  VERSION: ${{ inputs.VERSION || '' }}

jobs:
  build-docker-core:
    runs-on: ubuntu-latest
    name: Build Docker Image Core
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update Version Info
        if: ${{ inputs.VERSION == '' }}
        run: |
          VERSION=$(go run scripts/build.go -version-info)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Download Web Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: web/dist/

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update Version Info
        if: ${{ inputs.VERSION == '' }}
        run: |
          VERSION=$(go run scripts/build.go -version-info)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mediatools
          tags: |
            type=raw,value=latest,enable=${{ env.IS_LATEST }}
            type=raw,value=${{ env.VERSION }},enable=true

      # - name: Show Information
      #   run: |
      #     echo "Docker镜像版本的标签号：${{ steps.build-info.outputs.version }}"
      #     echo "Git提交版本号：${{ steps.build-info.outputs.git-commit }}"
      #     echo "构建时间：${{ steps.build-info.outputs.built-at }}"
      #     echo "是否发布为Docker镜像最新版本：${{ env.IS_LATEST }}"

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.ci
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/s390x
          push: true
          # build-args: |
          #   APP_VERSION=${{ steps.build-info.outputs.version }}
          #   APP_GIT_COMMIT=${{ steps.build-info.outputs.git-commit }}
          #   APP_BUILT_AT=${{ steps.build-info.outputs.built-at }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}-docker
          cache-to: type=gha, scope=${{ github.workflow }}-docker
